version: "3.9"

services:
  app:
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    build: .
    container_name: apiemsclinica-app
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    env_file:
      - ${ENV_FILE:-.env.development}
    restart: unless-stopped
    networks:
      - ems

  redis:
    image: redis:7-alpine
    container_name: emsclinica-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    networks:
      - ems

networks:
  ems:
    driver: bridge

volumes:
  redisdata:
