services:
  db:
    image: postgres:17-alpine
    container_name: emsclinica-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-emsclinica_dev}
      TZ: America/Araguaina
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks: [ems]

  pgadmin:
    image: dpage/pgadmin4
    container_name: emsclinica-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped
    networks: [ems]

networks:
  ems:
    driver: bridge

volumes:
  pgdata:
  pgadmindata:
