version: "3"

services:

  redis:
    image: bitnami/redis:latest
    container_name: emsclinica-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    ports: ["3333:3333"]
    volumes: [".:/home/node/app"]
    env_file: [.env.production]   # << credenciais de PROD
    depends_on:
      - db
      - redis

  pgadmin:
    image: dpage/pgadmin4
    container_name: emsclinica-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db
