services:
  app:
    build: .
    container_name: apiemsclinica-app
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    env_file:
      - .env.production
    restart: unless-stopped
